Sanitise SearchableText when querying catalog in search and filter
collective/collective.collectionfilter pull request #96
Opened 2019-12-06 16:45 UTC by JeffersonBledsoe

2019-12-07 11:37 UTC, djay commented
I'm suprised there is not code we can call tondo this already without having to repeat the code here?

2019-12-07 11:37 UTC, djay commented
I'm suprised there is not code we can call tondo this already without having to repeat the code here?

2020-01-15 12:25 UTC, petschki commented on src/collective/collectionfilter/query.py
> +    return u" ".join(clean_query)
There is similar code here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py#L23 ... maybe you can reuse it in some way?

2021-02-09 16:10 UTC, JeffersonBledsoe commented
@petschki Would you mind taking a look through this again? If it's good, would you mind squashing & merging rather than a standard merge, this isn't my cleanest of PRs! 😳

2021-03-18 09:29 UTC, instification commented
@thet @petschki is it possible to get this PR reviewed/merged?

2021-03-18 09:40 UTC, petschki requested changes
Can you rebase this on master in order to get the tests running again?

2021-03-18 10:03 UTC, JeffersonBledsoe commented
@petschki Looks like the setup step for the tests wasn't working correctly. Should be fixed now, waiting on the tests!

2021-03-18 10:36 UTC, petschki approved these changes
Lgtm

2021-03-18 10:36 UTC, merged